- name: Installation des prérequis
  hosts: Ubuntu
  remote_user: root
 
  tasks:
 
    - name: Ajout du repository
      apt_repository:
        repo: ppa:jonathonf/python-3.6

    - name: apt update
      apt:
        upgrade: dist

    - name: Installation de Python3
      apt:
        name: python3.6
        state: latest

    - name: Installation de pip3
      apt:
        name: python3-pip
        state: latest

    - name: Installation de git
      apt:
        name: git
        state: latest
